# Generated by Django 4.2.3 on 2023-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('bdy', models.TextField(max_length=10000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentFirstName', models.CharField(max_length=50)),
                ('studentMiddleName', models.CharField(max_length=50)),
                ('studentLastName', models.CharField(max_length=50)),
                ('studentGender', models.CharField(max_length=50)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentPhone', models.IntegerField()),
                ('studentLevel', models.CharField(max_length=50)),
                ('studentCourse', models.CharField(max_length=50)),
                ('studentCountry', models.CharField(blank=True, max_length=50)),
                ('parentPhone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityName', models.CharField(max_length=50)),
                ('universityCountry', models.CharField(max_length=50)),
                ('universityContinent', models.CharField(max_length=50)),
            ],
        ),
    ]
